#!/usr/bin/env python

import sys
import requests
from bs4 import BeautifulSoup

# spits out page title & body text. less tokens for llm


def fetchtext(url):
    try:
        response = requests.get(url)
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"Error: {e}")
        return

    soup = BeautifulSoup(response.content, 'html.parser')
    title_element = soup.find('title')
    title = title_element.text if title_element else ''
    body_text = ' '.join(p.text for p in soup.find_all('p'))

    print(f"title: {title}\n\n{body_text}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: fetchsum <URL>")
        sys.exit(1)

    fetchtext(sys.argv[1])
